name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade poetry
          poetry install

      - name: Test
        shell: bash
        run: |
          poetry run pytest --cov=django_dramatiq_email --cov-report term:skip-covered tests/
          poetry run coverage xml

      - name: Report Coverage
        if: matrix.python-version == '3.8'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
